module.exports = [{
  Prop_ID: 'X002',
  Name: 'Bronx Park',
  Location: 'Bronx Park East and Brady Ave.',
  Phone: '(718) 430-1821',
  Courts: '6',
  Indoor_Outdoor: 'Outdoor',
  Tennis_Type: 'Hard',
  Accessible: 'N',
  Info: null,
  lat: '40.8511',
  lon: '-73.8704'
},
{
  Prop_ID: 'X010',
  Name: 'Cary Leeds Tennis Center at Crotona Park',
  Location: 'E. 173d St. and Crotona Ave.',
  Phone: '(718) 247-7420',
  Courts: '22',
  Indoor_Outdoor: 'Indoor',
  Tennis_Type: 'Hard',
  Accessible: 'Y',
  Info: 'Lessons are offered. During the indoor season (The day after Columbus Day &ndash; April 27), there are 10 outdoor courts available, and 10 courts are bubbled and can be rented for a fee. During the outdoor season, there are 15 courts available to Parks tennis permit holders. For booking courts and program information please call or visit <a href="http://www.nyjtl.org/caryleeds/">Cary Leeds Tennis Center\'s</a> website for more information.',
  lat: '40.8394',
  lon: '-73.8951'
},
{
  Prop_ID: 'X196',
  Name: 'Haffen Park',
  Location: 'Hammersley, Ely, and Gunther Aves.',
  Phone: '(718) 379-8347',
  Courts: '6',
  Indoor_Outdoor: 'Outdoor',
  Tennis_Type: 'Hard',
  Accessible: 'Y',
  Info: null,
  lat: '40.874',
  lon: '-73.84'
},
{
  Prop_ID: 'X201',
  Name: 'Seton Park',
  Location: 'W. 232nd to 235th St., Palisade and Independence Aves.',
  Phone: '(718) 601-6044',
  Courts: '6',
  Indoor_Outdoor: 'Outdoor',
  Tennis_Type: 'Hard',
  Accessible: 'N',
  Info: 'Lessons Offered',
  lat: '40.8853',
  lon: '-73.9164'
},
{
  Prop_ID: 'X044',
  Name: 'St. James Park',
  Location: 'Jerome Ave. and E. 193d St.',
  Phone: '(718) 822-4271',
  Courts: '4',
  Indoor_Outdoor: 'Outdoor',
  Tennis_Type: 'Hard',
  Accessible: 'Y',
  Info: null,
  lat: '40.8656',
  lon: '-73.8972'
},
{
  Prop_ID: 'X104',
  Name: 'Williamsbridge Oval',
  Location: 'E. 208th St. and Bainbridge Ave.',
  Phone: '(718) 654-1851',
  Courts: '8',
  Indoor_Outdoor: 'Outdoor',
  Tennis_Type: 'Hard',
  Accessible: 'N',
  Info: null,
  lat: '40.8782',
  lon: '-73.8777'
},
{
  Prop_ID: 'B215',
  Name: 'Decatur Playground',
  Location: 'Decatur bet. Summer and Lewis Aves.',
  Phone: '(718) 493-7612',
  Courts: '1',
  Indoor_Outdoor: 'Outdoor',
  Tennis_Type: 'Hard',
  Accessible: 'N',
  Info: null,
  lat: '40.6814',
  lon: '-73.9363'
},
{
  Prop_ID: 'B028',
  Name: 'Lucille Ferrera Tennis Courts (Dyker Beach Park)',
  Location: 'Cropsey Avenue, Bay 8th Street and Poly Place',
  Phone: '(718) 259-4016',
  Courts: '9',
  Indoor_Outdoor: 'Outdoor',
  Tennis_Type: 'Hard',
  Accessible: 'Y',
  Info: null,
  lat: '40.6063',
  lon: '-74.0166'
},
{
  Prop_ID: 'B032',
  Name: 'Ft. Greene Park',
  Location: 'DeKalb & S. Portland Aves.',
  Phone: '(718) 722-3218',
  Courts: '6',
  Indoor_Outdoor: 'Outdoor',
  Tennis_Type: 'Hard',
  Accessible: 'N',
  Info: 'Lessons Offered',
  lat: '40.6906',
  lon: '-73.9757'
},
{
  Prop_ID: 'B372',
  Name: 'Friends Field',
  Location: 'Ave. L & East 4th St.',
  Phone: '(718) 965-6502',
  Courts: '2',
  Indoor_Outdoor: 'Outdoor',
  Tennis_Type: 'Hard',
  Accessible: 'Y',
  Info: null,
  lat: '40.6184',
  lon: '-73.9722'
},
{
  Prop_ID: 'B294',
  Name: 'Jackie Robinson',
  Location: 'Malcolm X. Blvd. & Chauncey St.',
  Phone: '(718) 622-0025',
  Courts: '4',
  Indoor_Outdoor: 'Outdoor',
  Tennis_Type: 'Hard',
  Accessible: 'N',
  Info: null,
  lat: '40.6803',
  lon: '-73.9278'
},
{
  Prop_ID: 'B210W',
  Name: 'J.J. Carty',
  Location: '95 Street & Fort Hamilton Pkwy.',
  Phone: '(718) 439-4296',
  Courts: '10',
  Indoor_Outdoor: 'Outdoor',
  Tennis_Type: 'Hard',
  Accessible: 'N',
  Info: null,
  lat: '40.6115',
  lon: '-74.0316'
},
{
  Prop_ID: 'B166D',
  Name: 'Joseph T. McGuire Park',
  Location: 'Avenue W and Bergen',
  Phone: null,
  Courts: '3',
  Indoor_Outdoor: 'Outdoor',
  Tennis_Type: 'Hard',
  Accessible: 'Y',
  Info: null,
  lat: '40.62',
  lon: '-73.8987'
},
{
  Prop_ID: 'B129',
  Name: 'Kaiser Playground',
  Location: 'Neptune Ave. & W. 25th St.',
  Phone: '(718) 946-1357',
  Courts: '12',
  Indoor_Outdoor: 'Outdoor',
  Tennis_Type: 'Hard',
  Accessible: 'Y',
  Info: 'Lessons Offered',
  lat: '40.5785',
  lon: '-73.9946'
},
{
  Prop_ID: 'B052',
  Name: 'Leif Ericson Park',
  Location: '8th Ave. & 66th St.',
  Phone: '(718) 259-4016',
  Courts: '9',
  Indoor_Outdoor: 'Outdoor',
  Tennis_Type: 'Hard',
  Accessible: 'N',
  Info: 'Lessons Offered',
  lat: '40.6319',
  lon: '-74.0137'
},
{
  Prop_ID: 'B054',
  Name: 'Lincoln Terrace Park',
  Location: 'Buffalo & Rochester Aves.',
  Phone: '(718) 804-7077',
  Courts: '11',
  Indoor_Outdoor: 'Outdoor',
  Tennis_Type: 'Hard',
  Accessible: 'N',
  Info: 'Lessons Offered',
  lat: '40.6665',
  lon: '-73.9255'
},
{
  Prop_ID: 'B214',
  Name: 'Linden Playground',
  Location: 'Linden Blvd. & Vermont St.',
  Phone: '(718) 927-2059',
  Courts: '8',
  Indoor_Outdoor: 'Outdoor',
  Tennis_Type: 'Hard',
  Accessible: 'N',
  Info: null,
  lat: '40.6584',
  lon: '-73.887'
},
{
  Prop_ID: 'B251',
  Name: 'Manhattan Beach',
  Location: 'Oriental Blvd.',
  Phone: '(718) 646-5913',
  Courts: '6',
  Indoor_Outdoor: 'Outdoor',
  Tennis_Type: 'Hard',
  Accessible: 'Y',
  Info: 'Lessons Offered',
  lat: '40.5777',
  lon: '-73.9399'
},
{
  Prop_ID: 'B057',
  Name: 'Marine Park',
  Location: 'Fillmore Ave. & Stuart St.',
  Phone: '(718) 376-1675',
  Courts: '15',
  Indoor_Outdoor: 'Outdoor',
  Tennis_Type: 'Hard',
  Accessible: 'Y',
  Info: 'Lessons Offered',
  lat: '40.6079',
  lon: '-73.935'
},
{
  Prop_ID: 'B058',
  Name: 'McCarren Tennis Center',
  Location: 'North 13th Street Between Berry Street and Bedford Avenue',
  Phone: '(347) 873-9698',
  Courts: '7',
  Indoor_Outdoor: 'Indoor',
  Tennis_Type: 'Hard',
  Accessible: 'N',
  Info: 'Lessons are offered. All 7 courts are bubbled during the indoor season (the day after Columbus Day-April 27) and may be rented for a fee. During the outdoor season, there are 6 courts available to Parks tennis permit holders. For bookings or for more information about tennis at McCarren Park, please email <a href="mailto:nycmccarrentennis@gmail.com">nycmccarrentennis@gmail.com</a>, or visit <a href="http://www.mccarrentennis.net/">mccarrentennis.net</a>.',
  lat: '40.7218',
  lon: '-73.9547'
},
{
  Prop_ID: 'B244',
  Name: 'McDonald Avenue Playground',
  Location: 'McDonald Ave. & Ave. S',
  Phone: '(718) 946-1373',
  Courts: '7',
  Indoor_Outdoor: 'Outdoor',
  Tennis_Type: 'Hard',
  Accessible: 'N',
  Info: null,
  lat: '40.6',
  lon: '-73.9722'
},
{
  Prop_ID: 'B050',
  Name: 'One Van Voorhees Park',
  Location: 'Pacific, Congress and Hicks Streets',
  Phone: '(718) 722-3213',
  Courts: '2',
  Indoor_Outdoor: 'Outdoor',
  Tennis_Type: 'Hard',
  Accessible: 'N',
  Info: null,
  lat: '40.6898',
  lon: '-74.0001'
},
{
  Prop_ID: 'B073',
  Name: 'Prospect Park Tennis Center',
  Location: 'Parkside Ave at the Parade Ground',
  Phone: '(718) 436-2500',
  Courts: '11',
  Indoor_Outdoor: 'Outdoor',
  Tennis_Type: 'Clay',
  Accessible: 'N',
  Info: 'Lessons are available. During the indoor season (October 23-May 6), there are 11 bubbled courts that may be rented for a fee. During the outdoor season, 8 courts are available to Parks tennis permit holders.  For more information, visit the <a href="https://www.prospectpark.org/visit-the-park/places-to-go/tennis-center/">Prospect Park Alliance tennis page</a>.',
  lat: '40.6513',
  lon: '-73.97'
},
{
  Prop_ID: 'B082',
  Name: 'Shore Road Playground',
  Location: 'Shore Rd. & 95th St.',
  Phone: '(718) 259-4016',
  Courts: '4',
  Indoor_Outdoor: 'Outdoor',
  Tennis_Type: 'Hard',
  Accessible: 'N',
  Info: 'Lessons Offered',
  lat: '40.6125',
  lon: '-74.037'
},
{
  Prop_ID: 'M144',
  Name: 'Brian Watkins Tennis Center',
  Location: 'At Houston St. (walk east over FDR Drive)',
  Phone: '(212) 219-0258',
  Courts: '12',
  Indoor_Outdoor: 'Outdoor',
  Tennis_Type: 'Hard',
  Accessible: 'N',
  Info: 'Lessons Offered',
  lat: '40.7156',
  lon: '-73.975'
},
{
  Prop_ID: 'M028',
  Name: 'Fort Washington Park',
  Location: 'Hudson River at 170th St.',
  Phone: '(212) 304-2322',
  Courts: '10',
  Indoor_Outdoor: 'Outdoor',
  Tennis_Type: 'Hard',
  Accessible: 'N',
  Info: 'Lessons Offered',
  lat: '40.8488',
  lon: '-73.9462'
},
{
  Prop_ID: 'M159',
  Name: 'Frederick Johnson Playground',
  Location: '151st St. east of 7th Ave.',
  Phone: '(212) 234-9609',
  Courts: '8',
  Indoor_Outdoor: 'Outdoor',
  Tennis_Type: 'Hard',
  Accessible: 'N',
  Info: 'Lessons Offered',
  lat: '40.825',
  lon: '-73.9356'
},
{
  Prop_ID: 'M042',
  Name: 'Inwood Hill Park',
  Location: '207th St. and Seaman Ave.',
  Phone: '(212) 304-2381',
  Courts: '9',
  Indoor_Outdoor: 'Outdoor',
  Tennis_Type: 'Hard',
  Accessible: 'Y',
  Info: 'Lessons Offered',
  lat: '40.8697',
  lon: '-73.9217'
},
{
  Prop_ID: 'Q004',
  Name: 'Astoria Park',
  Location: '21st St. & Hoyt Ave.',
  Phone: '(718) 626-8136',
  Courts: '14',
  Indoor_Outdoor: 'Outdoor',
  Tennis_Type: 'Hard',
  Accessible: 'N',
  Info: 'Lessons Offered',
  lat: '40.7756',
  lon: '-73.9243'
},
{
  Prop_ID: 'Q005',
  Name: 'Baisley Park',
  Location: '155th St. & 118th Ave.',
  Phone: '(718) 352-4793',
  Courts: '4',
  Indoor_Outdoor: 'Outdoor',
  Tennis_Type: 'Hard',
  Accessible: 'N',
  Info: null,
  lat: '40.6808',
  lon: '-73.7872'
},
{
  Prop_ID: 'Q005',
  Name: 'Baisley South',
  Location: 'N. Conduit Ave. & 150th St.',
  Phone: '(718) 352-4793',
  Courts: '4',
  Indoor_Outdoor: 'Outdoor',
  Tennis_Type: 'Hard',
  Accessible: 'N',
  Info: null,
  lat: '40.6696',
  lon: '-73.7884'
},
{
  Prop_ID: 'Q460',
  Name: 'Broad Channel Park',
  Location: 'Crossbay Blvd. and E. 16-E. 18 Rds.',
  Phone: '(718) 318-4000',
  Courts: '2',
  Indoor_Outdoor: 'Outdoor',
  Tennis_Type: 'Hard',
  Accessible: 'N',
  Info: null,
  lat: '40.6005',
  lon: '-73.8196'
},
{
  Prop_ID: 'Q008',
  Name: 'Brookville Park',
  Location: 'Brookville Blvd. & Southern Pkwy.',
  Phone: '(718) 255-2620',
  Courts: '6',
  Indoor_Outdoor: 'Outdoor',
  Tennis_Type: 'Hard',
  Accessible: 'N',
  Info: 'Lessons Offered',
  lat: '40.6614',
  lon: '-73.7442'
},
{
  Prop_ID: 'Q121',
  Name: 'Det. Keith L. Williams Park',
  Location: 'Liberty Ave. & 173rd St.',
  Phone: '(718) 352-4793',
  Courts: '10',
  Indoor_Outdoor: 'Outdoor',
  Tennis_Type: 'Hard',
  Accessible: 'Y',
  Info: null,
  lat: '40.7035',
  lon: '-73.7849'
},
{
  Prop_ID: 'Q015',
  Name: 'Forest Park',
  Location: 'Park Lane South & 89th St.',
  Phone: '(718) 235-5871',
  Courts: '14',
  Indoor_Outdoor: 'Outdoor',
  Tennis_Type: 'Hard',
  Accessible: 'Y',
  Info: null,
  lat: '40.6976',
  lon: '-73.8557'
},
{
  Prop_ID: 'Q020',
  Name: 'Highland Park- Lower Playground',
  Location: 'Elton St. & Jamaica Ave.',
  Phone: '(718) 235-5871',
  Courts: '18',
  Indoor_Outdoor: 'Outdoor',
  Tennis_Type: 'Hard',
  Accessible: 'N',
  Info: '10 full courts, 8 36-foot youth courts.',
  lat: '40.6836',
  lon: '-73.8884'
},
{
  Prop_ID: 'Q102',
  Name: 'Juniper Valley Park',
  Location: '62nd Ave. & 80th St.',
  Phone: '(718) 326-2877',
  Courts: '8',
  Indoor_Outdoor: 'Outdoor',
  Tennis_Type: 'Hard',
  Accessible: 'N',
  Info: 'Lessons Offered',
  lat: '40.7204',
  lon: '-73.876'
},
{
  Prop_ID: 'Q369',
  Name: 'Louis Pasteur Park',
  Location: '52 Ave. & Marathon Pkwy.',
  Phone: null,
  Courts: '2',
  Indoor_Outdoor: 'Outdoor',
  Tennis_Type: 'Hard',
  Accessible: 'N',
  Info: null,
  lat: '40.7617',
  lon: '-73.735'
},
{
  Prop_ID: 'Q007',
  Name: 'Michaelis Bayswater Park',
  Location: '32nd St. & Dickens Ave.',
  Phone: '(718) 318-4000',
  Courts: '6',
  Indoor_Outdoor: 'Outdoor',
  Tennis_Type: 'Hard',
  Accessible: 'N',
  Info: null,
  lat: '40.5986',
  lon: '-73.7683'
},
{
  Prop_ID: 'Q131',
  Name: 'Maurice Park',
  Location: 'Maurice Ave., LIE Service Rd. Westbound',
  Phone: '(718) 326-2877',
  Courts: '2',
  Indoor_Outdoor: 'Outdoor',
  Tennis_Type: 'Hard',
  Accessible: 'N',
  Info: null,
  lat: '40.7274',
  lon: '-73.904'
},
{
  Prop_ID: 'Q092',
  Name: 'Police Officer Edward Byrne Park',
  Location: 'North Conduit Ave. & 134-135 Street',
  Phone: '(718) 352-4793',
  Courts: '4',
  Indoor_Outdoor: 'Outdoor',
  Tennis_Type: 'Hard',
  Accessible: 'N',
  Info: null,
  lat: '40.6672',
  lon: '-73.8071'
},
{
  Prop_ID: 'Q371',
  Name: 'Rockaway Community Park',
  Location: 'Alamdea Ave. btwn B51 & B56',
  Phone: '(718) 318-4000',
  Courts: '3',
  Indoor_Outdoor: 'Outdoor',
  Tennis_Type: 'Hard',
  Accessible: 'N',
  Info: null,
  lat: '40.5985',
  lon: '-73.7835'
},
{
  Prop_ID: 'Q448',
  Name: 'Roy Wilkins Park',
  Location: 'Merrick Blvd. & 119 Ave.',
  Phone: '(718) 276-8690',
  Courts: '4',
  Indoor_Outdoor: 'Outdoor',
  Tennis_Type: 'Hard',
  Accessible: 'N',
  Info: null,
  lat: '40.686',
  lon: '-73.77'
},
{
  Prop_ID: 'Q107',
  Name: 'Springfield Park',
  Location: '147 Ave. & Springfield Ave.',
  Phone: '(718) 225-2620',
  Courts: '2',
  Indoor_Outdoor: 'Outdoor',
  Tennis_Type: 'Hard',
  Accessible: 'N',
  Info: null,
  lat: '40.6598',
  lon: '-73.7623'
},
{
  Prop_ID: 'Q051',
  Name: 'St. Albans Park',
  Location: 'Merrick Blvd. & 172nd St.',
  Phone: '(718) 352-4793',
  Courts: '2',
  Indoor_Outdoor: 'Outdoor',
  Tennis_Type: 'Hard',
  Accessible: 'N',
  Info: null,
  lat: '40.6939',
  lon: '-73.7801'
},
{
  Prop_ID: 'Q413',
  Name: 'Victor Hanson Community Center (Rochdale Park)',
  Location: 'Guy Brewer Blvd. & 134th Ave.',
  Phone: '(718) 978-1536',
  Courts: '6',
  Indoor_Outdoor: 'Outdoor',
  Tennis_Type: 'Hard',
  Accessible: 'N',
  Info: null,
  lat: '40.6744',
  lon: '-73.7739'
},
{
  Prop_ID: 'Q303',
  Name: 'Travers Park',
  Location: '77 & 78 Sts. at 34 Ave. & Northern Blvd',
  Phone: '(718) 426-4347',
  Courts: '1',
  Indoor_Outdoor: 'Outdoor',
  Tennis_Type: 'Hard',
  Accessible: 'N',
  Info: null,
  lat: '40.7539',
  lon: '-73.8891'
},
{
  Prop_ID: 'Q373',
  Name: 'East Elmhurst (PS 127)',
  Location: '25 Ave. & 98 St.-100 St.',
  Phone: '(718) 426-4347',
  Courts: '1',
  Indoor_Outdoor: 'Outdoor',
  Tennis_Type: 'Hard',
  Accessible: 'N',
  Info: null,
  lat: '40.7651',
  lon: '-73.8707'
},
{
  Prop_ID: 'R123',
  Name: 'Skyline Park',
  Location: 'Arnold St. & Prospect Ave.',
  Phone: '(718) 667-3545',
  Courts: '2',
  Indoor_Outdoor: 'Outdoor',
  Tennis_Type: 'All Weather',
  Accessible: 'N',
  Info: null,
  lat: '40.6396',
  lon: '-74.0898'
},
{
  Prop_ID: 'R022',
  Name: 'Silver Lake Park',
  Location: 'Hart Blvd. & Revere St.',
  Phone: '(718) 667-3545',
  Courts: '4',
  Indoor_Outdoor: 'Outdoor',
  Tennis_Type: 'All Weather',
  Accessible: 'N',
  Info: 'Lessons Offered',
  lat: '40.6278',
  lon: '-74.0996'
},
{
  Prop_ID: 'R015',
  Name: 'Walker Park',
  Location: 'Bard Ave. & Delafield Place',
  Phone: '(718) 667-3545',
  Courts: '6',
  Indoor_Outdoor: 'Outdoor',
  Tennis_Type: 'All Weather',
  Accessible: 'N',
  Info: 'Lessons Offered',
  lat: '40.6433',
  lon: '-74.1087'
},
{
  Prop_ID: 'R030',
  Name: 'Willowbrook Park',
  Location: 'Richmond Ave. & Eton Place',
  Phone: '(718) 667-3545',
  Courts: '6',
  Indoor_Outdoor: 'Outdoor',
  Tennis_Type: 'All Weather',
  Accessible: 'Y',
  Info: null,
  lat: '40.6038',
  lon: '-74.1613'
},
{
  Prop_ID: 'R031',
  Name: 'Wolfe\'s Pond Park',
  Location: 'Cornelia Ave., off of Hylan Blvd.',
  Phone: '(718) 667-3545',
  Courts: '2',
  Indoor_Outdoor: 'Outdoor',
  Tennis_Type: 'All Weather',
  Accessible: 'Y',
  Info: 'Lessons Offered',
  lat: '40.5194',
  lon: '-74.1868'
},
{
  Prop_ID: 'M104',
  Name: 'Sportime at Randall\'s Island',
  Location: 'Randall\'s Island Park',
  Phone: '(212) 427-6150',
  Courts: '20',
  Indoor_Outdoor: 'Indoor',
  Tennis_Type: 'Hard',
  Accessible: 'N',
  Info: 'The Sportime Tennis Center is a concession offering 5 indoor hard courts, 5 indoor/outdoor hard courts, and 10 indoor/outdoor clay courts. Ten of its 20 courts (or 50 percent of available courts when courts are out of service for maintenance, repairs, etc.) are available to <a href="/things-to-do/tennis">NYC Parks Tennis Permit</a> holders during the outdoor permit season (May 1 through the day before Columbus Day; 7am to 7pm), weather permitting. For more information, visit the <a href="http://www.sportimeny.com/manhattan">Sportime Randall\'s Island tennis page</a>.',
  lat: '40.7943',
  lon: '-73.9198'
},
{
  Prop_ID: 'M070',
  Name: 'Sutton Tennis at Queensboro Oval',
  Location: 'York Ave. Between E 59 St. & E 60 St.',
  Phone: '(212) 751-3452',
  Courts: '8',
  Indoor_Outdoor: 'Indoor',
  Tennis_Type: 'Clay',
  Accessible: 'Y',
  Info: 'Lessons are offered. Six courts are available to NYC Parks tennis permit holders from June 16 - September 10. For booking courts and program information please call or visit <a href="http://www.suttoneasttennis.com/pages/index.cfm?siteid=9370">Sutton East Tennis Club\'s</a> website.',
  lat: '40.7594',
  lon: '-73.9602'
},
{
  Prop_ID: 'Q001A',
  Name: 'Alley Pond Tennis Center',
  Location: 'Queens Village 79-20 Winchester Boulevard',
  Phone: '(718) 264-2600',
  Courts: '16',
  Indoor_Outdoor: 'Indoor',
  Tennis_Type: 'Hard',
  Accessible: 'N',
  Info: null,
  lat: '40.7394',
  lon: '73.7361'
},
{
  Prop_ID: 'B407',
  Name: 'South Oxford Park',
  Location: 'Cumberland Street between Atlantic Commons and Atlantic Avenue',
  Phone: null,
  Courts: '2',
  Indoor_Outdoor: 'Outdoor',
  Tennis_Type: 'Hard',
  Accessible: null,
  Info: null,
  lat: '40.6836',
  lon: '-73.9722'
},
{
  Prop_ID: 'X210',
  Name: 'Governor Smith Playground',
  Location: 'Morris Avenue between E. 151 and E. 153 Streets',
  Phone: null,
  Courts: '3',
  Indoor_Outdoor: 'Outdoor',
  Tennis_Type: 'Hard',
  Accessible: null,
  Info: null,
  lat: '40.8196',
  lon: '-73.9202'
},
{
  Prop_ID: 'M308',
  Name: 'Washington Market Park',
  Location: 'Chambers St. & West St.',
  Phone: null,
  Courts: '1',
  Indoor_Outdoor: 'Outdoor',
  Tennis_Type: 'Hard',
  Accessible: null,
  Info: null,
  lat: '40.7171',
  lon: '-74.0123'
},
{
  Prop_ID: 'B025',
  Name: 'Cooper Park Tennis Courts',
  Location: 'Morgan Ave, between Maspeth Ave and Sharon St',
  Phone: null,
  Courts: '2',
  Indoor_Outdoor: 'Outdoor',
  Tennis_Type: 'Hard',
  Accessible: 'N',
  Info: null,
  lat: '40.716',
  lon: '-73.9364'
}];